gallery/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', login, {'template_name': 'registration/login.html'}),
    url(r'^logout/$', logout, {'template_name': 'registration/logged_out.html'}),
    url(r'^register/$', views.register, name='register'),
    url(r'^album/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<pk>[0-9]+)/$', views.AlbumDateDetail.as_view(month_format='%m'), name='album-detail'),
    url(r'^album/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$', views.AlbumDayArchiveView.as_view(month_format='%m'), name='gallery-archive-day'),
    url(r'^album/(?P<year>\d{4})/(?P<month>[0-9]{2})/$', views.AlbumMonthArchiveView.as_view(month_format='%m'), name='gallery-archive-month'),
    url(r'^album/(?P<year>\d{4})/$', views.AlbumYearArchiveView.as_view(), name='pl-gallery-archive-year'),
    url(r'^album/$', views.AlbumArchiveIndexView.as_view(), name='pl-gallery-archive'),
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumDetail.as_view(), name='pl-gallery'),
    url(r'^albumlist/$', views.AlbumList.as_view(), name='album-list'), 
    url(r'^album/new/$', views.album_new, name='album_new'),
    url(r'^album/change/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album_update'),
    url(r'^album/delete/(?P<pk>[0-9]+)/$', views.AlbumDelete.as_view(), name='album_delete'),
    
    url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<pk>[0-9]+)/$', views.PhotoDateDetail.as_view(month_format='%m'), name='photo-detail'),
    url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$', views.PhotoDayArchiveView.as_view(month_format='%m'), name='photo-archive-day'),
    url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/$', views.PhotoMonthArchiveView.as_view(month_format='%m'), name='photo-archive-month'),
    url(r'^photo/(?P<year>\d{4})/$', views.PhotoYearArchiveView.as_view(), name='pl-photo-archive-year'),
    url(r'^photo/$', views.PhotoArchiveIndexView.as_view(), name='pl-photo-archive'),
    url(r'^photo/(?P<pk>[0-9]+)/$', views.PhotoDetail.as_view(), name='pl-photo'),
    url(r'^photolist/$', views.PhotoList.as_view(), name='photo-list'),
    url(r'^photo/new/$', views.PhotoAdd.as_view(), name='photo_new'),
    url(r'^photo/change/(?P<pk>[0-9]+)/$', views.PhotoUpdate.as_view(), name='photo_change'),
    url(r'^photo/delete/(?P<pk>[0-9]+)/$', views.PhotoDelete.as_view(), name='photo_delete'),

    
]

www/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

app_name = 'gallery'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('gallery.urls', namespace='gallery')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
import random
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.core.urlresolvers import reverse
from django.conf import settings
from .managers import AlbumQuerySet, PhotoQuerySet
from django.db.models import permalink

LATEST_LIMIT = getattr(settings, 'GALLERY_ALBUM_LATEST_LIMIT', None)
SAMPLE_SIZE = getattr(settings, 'GALLERY_ALBUM_SAMPLE_SIZE', 5)



class Album(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=200, blank=False, verbose_name='Названия')
    description = models.TextField(verbose_name='Описания')
    created_d = models.DateTimeField(default=now)
    mod_d = models.DateTimeField(auto_now_add=False, auto_now=True)
    is_public = models.BooleanField(default=True)
    objects = AlbumQuerySet.as_manager()
    photos = models.ManyToManyField('Photo', related_name='photos', null=True, blank=True)


    class Meta:
        ordering = ["mod_d"]
        get_latest_by = 'created_d'

    def __str__(self):
        return "Альбом: %s, User: %s" % (self.title, self.user)
   
    def get_absolute_url(self):
        return reverse('gallery:pl-gallery', kwargs={'pk': self.pk})
 
    def latest(self, limit=LATEST_LIMIT, public=True):
        if not limit:
            limit = self.photo_count()
        if public:
            return self.public()[:limit]
        else:
            return self.photos.all()[:limit]

    def sample(self, count=None, public=True):
        if not count:
            count = SAMPLE_SIZE
        if count > self.photo_count():
            count = self.photo_count()
        if public:
            photo_set = self.public()
        else:
            photo_set = self.photos.filter(sites__id=settings.SITE_ID)
        return random.sample(set(photo_set), count)

    def photo_count(self, public=True):
        if public:
            return self.public().count()
        else:
            return self.photos.all().count()
    photo_count.short_description = 'count'

    def public(self):
        return self.photos.filter(is_public=True)

 

class Photo(models.Model):
    title = models.CharField(max_length=200, blank=False)    
    created_d = models.DateTimeField(default=now)
    mod_d = models.DateTimeField(auto_now_add=False, auto_now=True)
    description = models.CharField(max_length=200, blank=True)
    is_public = models.BooleanField(default=True)
    objects = PhotoQuerySet.as_manager()

    image = models.ImageField(upload_to='mediafiles/o/%Y-%m-%d')

    class Meta:
        ordering = ["mod_d"]
  
    def __str__(self):
        return self.title
 
    def save(self, *args, **kwargs):
        if self.pk is None:
            self.pk = self.id
        super(Photo, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('gallery:pl-photo', args=[self.id])

gallery/forms.py
from django import forms
from .models import Album, Photo


class AlbumForm(forms.ModelForm):
    class Meta: 
        model = Album
        fields = ['user', 'title', 'description', 'photos']
        

class PhotoForm(forms.ModelForm):
    class Meta: 
        model = Photo
        fields = ['image', 'title', 'description']

gallery/views.py
from django.views.generic.dates import ArchiveIndexView, DateDetailView, DayArchiveView, MonthArchiveView, YearArchiveView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from .models import Album, Photo
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .forms import AlbumForm, PhotoForm



def index(request):
    queryset = Album.objects.filter(is_public=True)
    return render(request, 'gallery/index.html')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/accounts/login/')
    else:
        form = UserCreationForm()

        args = {'form': form}
        return render(request, 'registration/reg_form.html', args)


class AlbumList(ListView):
    queryset = Album.objects.filter(is_public=True)


class AlbumDetail(DetailView):
    queryset = Album.objects.filter(is_public=True)



class AlbumDateDetail(DateDetailView):
    queryset = Album.objects.filter(is_public=True)
    date_field = 'created_d'
    allow_future = True


class AlbumArchiveIndexView(ArchiveIndexView):
    queryset = Album.objects.filter(is_public=True)
    date_field = 'created_d'
    allow_future = True


class AlbumDayArchiveView(DayArchiveView):
    queryset = Album.objects.filter(is_public=True)
    date_field = 'created_d'
    allow_future = True


class AlbumMonthArchiveView(MonthArchiveView):
    queryset = Album.objects.filter(is_public=True)
    date_field = 'created_d'
    allow_future = True


class AlbumYearArchiveView(YearArchiveView):
    queryset = Album.objects.filter(is_public=True)
    date_field = 'created_d'
    make_object_list = True
    allow_future = True

@login_required
def album_new(request):
    if request.method == "POST":
        form = AlbumForm(request.POST)
        if form.is_valid():
            album = form.save(commit=False)
            album.author = request.user
            album.save()
            return redirect('gallery:pl-gallery', pk=album.pk)
    else:
        form = AlbumForm()
    return render(request, 'gallery/album_edit.html', {'form': form})


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['user', 'title', 'description', 'photos']
    template_name = 'gallery/album_update_form.html'  

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('gallery:index')



class PhotoList(ListView):
    queryset = Photo.objects.filter(is_public=True)


class PhotoDetail(DetailView):
    queryset = Photo.objects.filter(is_public=True)


class PhotoDateDetail(DateDetailView):
    queryset = Photo.objects.filter(is_public=True)
    date_field = 'created_d'
    allow_future = True


class PhotoArchiveIndexView(ArchiveIndexView):
    queryset = Photo.objects.filter(is_public=True)
    date_field = 'created_d'
    allow_future = True


class PhotoDayArchiveView(DayArchiveView):
    queryset = Photo.objects.filter(is_public=True)
    date_field = 'created_d'
    allow_future = True


class PhotoMonthArchiveView(MonthArchiveView):
    queryset = Photo.objects.filter(is_public=True)
    date_field = 'created_d'
    allow_future = True


class PhotoYearArchiveView(YearArchiveView):
    queryset = Photo.objects.filter(is_public=True)
    date_field = 'created_d'
    make_object_list = True
    allow_future = True

class PhotoAdd(CreateView):
    model = Photo
    fields = ['image', 'title', 'description']

class PhotoUpdate(UpdateView):
    model = Photo
    fields = ['image', 'title', 'description']
    template_name = 'gallery/photo_update_form.html'

class PhotoDelete(DeleteView):
    model = Photo
    success_url = reverse_lazy('gallery:index')

gallery/templates/gallery/album_archive.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Новые альбомы{% endblock %}

{% block content %}


  <div class="container">
      <div id="page_content">
          <div class="row col-lg-12">
              {% if user.is_authenticated %}
              <div style="float:right;"><a href="{% url 'gallery:album_new' %}" class="btn btn-default">Создать альбом</a></div>
              <h1 class="page-header">Новые альбомы</h1> 
              {% else %}
              <h1 class="page-header">Новые альбомы</h1>
              {% endif %}
          </div>
	  <div class="row">
	      <aside class="col-md-2">
		  <h4>Фильтр по годам</h4>
		  <ul>
			{% for date in date_list %}
				<li><a href="{% url 'gallery:pl-gallery-archive-year' date.year %}">{{ date|date:"Y" }}</a></li>
			{% endfor %}
		  </ul>
              </aside>
              <main class="col-md-10">		      	
			{% if latest %}
			    {% for album in latest %}
			    	{% include "gallery/includes/album_sample.html" %}
			    {% endfor %}
			{% else %}
			    <p>No galleries were found</p>
{% endif %}
			
	      </main>
	  </div>
      </div>
  </div>
	
{% endblock %}

gallery/templates/gallery/album_archive_day.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_day=day|date:"d F Y" %}Альбомы {{ show_day }}{% endblocktrans %}{% endblock %}

{% block content %}
<div class="container">
    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_day=day|date:"d F Y" %}Альбомы {{ show_day }} года{% endblocktrans %}</h1>
    </div>

    <div class="row col-lg-12">
        {% if object_list %}
            {% for album in object_list %}
                {% include "gallery/includes/album_sample.html" %}
            {% endfor %}
        {% else %}
            <p>Не найдено по запросу</p>
        {% endif %}
    </div>
    
    <div><a href="{% url 'gallery:gallery-archive-month' day.year day|date:"m"|lower %}" class="btn btn-default">Все альбомы за месяц</a></div>
</div>
{% endblock %}

gallery/templates/gallery/album_archive_month.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_month=month|date:"F Y" %}Galleries for {{ show_month }}{% endblocktrans %}{% endblock %}

{% block content %}
<div class="container">
    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_month=month|date:"F Y" %}Альбомы {{ show_month }}{% endblocktrans %}</h1>
    </div>

    <div class="row">

        <aside class="col-md-2">

            <h4>Фильтр по дням</h4>
            <ul>
            {% for date in date_list %}
                <li><a href="{% url 'gallery:gallery-archive-day' date.year date|date:"m"|lower date.day %}">{{ date|date:"d" }}</a></li>
            {% endfor %}
            </ul>

        </aside>

        <main class="col-md-10">

            {% if object_list %}
                {% for album in object_list %}
                    {% include "gallery/includes/album_sample.html" %}
                {% endfor %}
            {% else %}
                <p>Не найдено по запросу фотографии</p>
            {% endif %}

            <div><a href="{% url 'gallery:pl-gallery-archive-year' month.year %}" class="btn btn-default">Все альбомы за год</a></div>

        </main>

    </div>
</div>
{% endblock %}

gallery/templates/gallery/album_archive_year.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_year=year|date:"Y" %}Galleries for {{ show_year }}{% endblocktrans %}{% endblock %}

{% block content %}
<div class="container">
    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_year=year|date:"Y" %}Альбомы {{ show_year }} года{% endblocktrans %}</h1>
    </div>

	<div class="row">

		<aside class="col-md-2">

			<h4>Фильтр по месяцам</h4>
			<ul>
				{% for date in date_list %}
					<li><a href="{% url 'gallery:gallery-archive-month' date.year date|date:"m"|lower %}">{{ date|date:"F" }}</a></li>
				{% endfor %}
			</ul>

		</aside>

		<main class="col-md-10">

			{% if object_list %}
				{% for album in object_list %}
			        {% include "gallery/includes/album_sample.html" %}
			    {% endfor %}
			{% else %}
			    <p>Не найдено по запросу фотографии</p>
			{% endif %}

		    <div><a href="{% url 'gallery:pl-gallery-archive' %}" class="btn btn-default">Все альбомы</a></div>

		</main>

	</div>
</div>
{% endblock %}

gallery/templates/gallery/album_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
<form action="" method="post">{% csrf_token %}
    <p>Вы точно хотите удалить "{{ object }}"?</p>
    <input type="submit" value="Удалить" />
</form>
</div>
{% endblock %}

gallery/templates/gallery/album_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ album.title }}{% endblock %}

{% block content %}
<div class="container">
<div class="row col-lg-12">
        <h1 class="page-header">{{ album.title }}</h1>
        <p class="muted"><small>Создано {{ album.created_d }}</small></p>        
        
{% for photo in album.public %}
	        <a href="{{ photo.get_absolute_url }}">
	             <img src="{{ photo.image.url }}" width="140" height="100" class="thumbnail" alt="{{ photo.title }}">
	        </a>
	    {% endfor %} 
	        
<br><br><br><br>


<div>
            {% if user.is_authenticated %}
	    	<a href="{% url 'gallery:album-list' %}" class="btn btn-default">Все альбомы</a>  
 	    	<a href="{% url 'gallery:album_update' album.id %}" class="btn btn-default">Изменить</a>
	    	<a href="{% url 'gallery:album_delete' album.id %}" class="btn btn-default">Удалить</a>
            {% else %}
            	<a href="{% url 'gallery:album-list' %}" class="btn btn-default">Все альбомы</a> 
            {% endif %}
 	</div></div></div>

 


{% endblock %}

gallery/templates/gallery/album_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "All galleries" %}{% endblock %}

{% block content %}
<div class="container">
    <div class="row col-lg-12">
        {% if user.is_authenticated %}
        <div style="float:right;"><a href="{% url 'gallery:album_new' %}" class="btn btn-default">Создать альбом</a></div>
        <h1 class="page-header">Все альбомы</h1>
        {% else %}
        <h1 class="page-header">Все альбомы</h1>
        {% endif %}
    </div>

    {% if album_list %}
        {% for album in album_list %}
            <div class="row col-lg-12">
                <h2><a href="{{ album.get_absolute_url }}">{{ album.title }}</a></h2>
                <p class="muted"><small>{% trans "Создано" %} {{ album.created_d }}</small></p>
                {% if album.description %}<p>{{ album.description|safe }}</p>{% endif %}
                
                    {% for photo in album.public %}
	        <a href="{{ photo.get_absolute_url }}">
	             <img src="{{ photo.image.url }}" width="140" height="100" class="thumbnail" alt="{{ photo.title }}">
	        </a>
	    {% endfor %} 
                
            </div>
        {% endfor %}
    {% else %}
        <div class="row col-lg-12">No galleries were found</div>
    {% endif %}
  </div>  
{% endblock %}

gallery/templates/gallery/album_update_form.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
</div>
{% endblock %}

gallery/templates/gallery/photo_archive.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% endblock %}

{% block content %}
  <div class="container">
    <div class="row col-lg-12">
        {% if user.is_authenticated %}
        <div style="float:right;"><a href="{% url 'gallery:photo_new' %}" class="btn btn-default">Добавить фото</a></div>
        <h1 class="page-header">Новые фотографии</h1>
        {% else %}
        <h1 class="page-header">Новые фотографии</h1>
        {% endif %}
    </div>

	<div class="row">
		
		<aside class="col-md-2">

			<h4>Сортировка по годам</h4>
			<ul>
			{% for date in date_list %}
				<li><a href="{% url 'gallery:pl-photo-archive-year' date.year %}">{{ date|date:"Y" }}</a></li>
			{% endfor %}
			</ul>

		</aside>

		<main class="col-md-10">
			
			{% if latest %}
			    {% for photo in latest %}
			        <a href="{{ photo.get_absolute_url }}">
			             <img src="{{ photo.image.url }}" width="140" height="100" class="thumbnail" alt="{{ photo.title }}">
			        </a>
			    {% endfor %}
			{% else %}
				<p>По вашему запросу ничего не найдено</p>
			{% endif %} 
			

		</main>

	</div>
</div>

{% endblock %}



gallery/templates/gallery/photo_archive_year.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_year=year|date:"Y" %}Photos for {{ show_year }}{% endblocktrans %}{% endblock %}


{% block content %}
<div class="container">
    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_year=year|date:"Y" %}Фотографии {{ show_year }} года{% endblocktrans %}</h1>
    </div>

	<div class="row">

		<aside class="col-md-2">

			<h4>Фильтр по месяцам</h4>
			<ul>
			{% for date in date_list %}
				<li><a href="{% url 'gallery:photo-archive-month' date.year date|date:"m"|lower %}">{{ date|date:"F" }}</a></li>
			{% endfor %}
			</ul>

		</aside>

		<main class="col-md-10">

			{% if object_list %}
				<div class="row col-lg-12">
				    {% for photo in object_list %}
				        <a href="{{ photo.get_absolute_url }}">
				             <img src="{{ photo.image.url }}" width="140" height="100" class="thumbnail" alt="{{ photo.title }}">
				        </a>
				    {% endfor %}
				</div>
			{% else %}
				<p>No photos were found</p>
			{% endif %}

		    <div><a href="{% url 'gallery:pl-photo-archive' %}" class="btn btn-default">Все фотографии</a></div>

		</main>

	</div></div>

{% endblock %}





gallery/templates/gallery/photo_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
<form action="" method="post">{% csrf_token %}
    <p>Вы точно хотите удалить "{{ object }}"?</p>
    <input type="submit" value="Удалить" />
</form>
</div>
{% endblock %}

gallery/templates/gallery/photo_detail.html
{% extends "base.html" %}


{% block title %}{{ object.title }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row col-lg-12">
        {% if user.is_authenticated %}
        <div class="dropdown" style="float:right; margin-top: 22px;">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Редактировать
                <span class="caret"></span>
            </button>
	    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
	        <li><a href="{% url 'gallery:photo_new' %}" >Добавить фото</a></li>
                <li><a href="{% url 'gallery:photo_change' photo.id %}">Изменить фото</a></li>
                <li><a href="{% url 'gallery:photo_delete' photo.id %}">Удалить фото</a></li>
	    </ul>
	</div>        
     
        <h1 class="page-header">{{ photo.title }}</h1>
        <p class="muted"><small>Создана {{ photo.created_d }}</small></p>
        {% else %}
        <h1 class="page-header">{{ photo.title }}</h1>
        <p class="muted"><small>Создана {{ photo.created_d }}</small></p>
        {% endif %}
        
    </div>

    <div class="row">
        <div class="col-md-6">
		    {% if photo.caption %}<p>{{ photo.caption|safe }}</p>{% endif %}


		
		    <a href="{{ photo.image.url }}">
		        <img src="{{ photo.image.url }}" class="img-responsive" alt="{{ photo.title }}">
		    </a>
		
                
        </div>

	<div class="col-lg-6">
		<p>{{ photo.description }}</p>

        <div class="col-md-6">
            {% if object.albums %}
                <p>Еще фотографии:</p>
                <table>
                    {% for album in albums %}
                        <tr>
                            <td>{% include previous_in_album.html %}</td>
	                        <td class="text-center"><a href="{{ album.get_absolute_url }}">{{ album.title }}</a></td>
	                        <td>{% include next_in_album.html %}</td>
                        </tr>
					{% endfor %}
				</table>
			{% endif %}
        </div>
    </div>
</div>
{% endblock %}

gallery/templates/gallery/photo_edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
   <h1>Добавить новое фото</h1>
   <form method="POST" class="post-form">{% csrf_token %}
       {{ form.as_p }}
       <button type="submit" class="save btn btn-default">Сохранить</button>
   </form>
</div>
{% endblock %}

gallery/templates/gallery/photo_update_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
   <h1>Изменить фото</h1>
   <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
       {{ form.as_p }}
       <button type="submit" class="save btn btn-default">Сохранить</button>
   </form>
</div>
{% endblock %}